import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

// Method 1: Generate PDF from structured data
export const generatePDFReport = async (reportData, dateRange, user) => {
  try {
    const doc = new jsPDF();
    
    // Add header
    doc.setFontSize(20);
    doc.text('DLP MONITORING REPORT', 20, 30);
    
    // Report info
    doc.setFontSize(12);
    doc.text(`Generated by: ${user?.name || 'DLP Field Officer'}`, 20, 50);
    doc.text(`Period: ${new Date(dateRange.startDate).toLocaleDateString()} - ${new Date(dateRange.endDate).toLocaleDateString()}`, 20, 60);
    doc.text(`Generated on: ${new Date().toLocaleDateString()}`, 20, 70);
    
    // Summary section
    doc.setFontSize(16);
    doc.text('SUMMARY', 20, 90);
    doc.setFontSize(12);
    doc.text(`Total Schools: ${reportData.summary.totalSchools}`, 20, 105);
    doc.text(`Total Visits: ${reportData.summary.totalVisits}`, 20, 115);
    doc.text(`Total Devices: ${reportData.summary.totalDevices}`, 20, 125);
    doc.text(`Working Devices: ${reportData.summary.workingDevices}`, 20, 135);
    doc.text(`Broken Devices: ${reportData.summary.brokenDevices}`, 20, 145);
    doc.text(`Missing Devices: ${reportData.summary.missingDevices}`, 20, 155);
    
    // Add a new page for visits
    doc.addPage();
    doc.setFontSize(16);
    doc.text('RECENT VISITS', 20, 20);
    
    let yPosition = 35;
    reportData.visits.forEach((visit, index) => {
      if (yPosition > 250) {
        doc.addPage();
        yPosition = 20;
      }
      
      doc.setFontSize(12);
      doc.text(`${visit.schoolName} - ${new Date(visit.visitDate).toLocaleDateString()}`, 20, yPosition);
      doc.text(`Notes: ${visit.notes}`, 20, yPosition + 7);
      yPosition += 20;
    });
    
    // Save the PDF
    doc.save(`DLP-Report-${new Date().toISOString().split('T')[0]}.pdf`);
    
  } catch (error) {
    console.error('PDF generation error:', error);
    throw new Error('Failed to generate PDF');
  }
};

// Method 2: Generate PDF from HTML content
export const generatePDFFromHTML = async (elementId, filename = 'DLP-Report.pdf') => {
  try {
    const element = document.getElementById(elementId);
    if (!element) {
      throw new Error('Report content not found');
    }

    const canvas = await html2canvas(element, {
      scale: 2,
      useCORS: true,
      logging: false
    });

    const imgData = canvas.toDataURL('image/png');
    const pdf = new jsPDF('p', 'mm', 'a4');
    const imgWidth = 210; // A4 width in mm
    const pageHeight = 295; // A4 height in mm
    const imgHeight = (canvas.height * imgWidth) / canvas.width;
    let heightLeft = imgHeight;
    let position = 0;

    pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
    heightLeft -= pageHeight;

    while (heightLeft >= 0) {
      position = heightLeft - imgHeight;
      pdf.addPage();
      pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
      heightLeft -= pageHeight;
    }

    pdf.save(filename);
  } catch (error) {
    console.error('HTML to PDF error:', error);
    throw new Error('Failed to generate PDF from HTML');
  }
};